# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Human Data Commons Foundation
email: info@humandatacommons.org
description: >
  Reclaim agency over your personal information,
  with the opportunity to contribute it to research
  on collective well-being
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://humandatacommons.org" # the base hostname & protocol for your site
twitter_username: hdcommons
github_username:  HumanDataCommons

# Frontpage settings
frontpage:
  header: >
    Instilling data collection practices with
    integrity and freedom
  lead: >
    Reclaim agency over your personal information,
    with the opportunity to contribute it to research
    on collective well-being

collections:
- frontpage_sections

# Build settings
markdown: kramdown
