# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Human Data Commons Foundation
email: info@humandatacommons.org
description: >
  Reclaim agency over your personal information,
  with the opportunity to make your data available
  for academics and researchers to further study
  across all aspects of human health, society, and culture
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://humandatacommons.org" # the base hostname & protocol for your site
twitter_username: hdcommons
github_username:  HumanDataCommons
reddit_sub: https://www.reddit.com/user/humandatacommons/m/hdc_foundation/top/
markdown: kramdown

# Collections
collections:
  frontpage_sections:
  tag_pages:
    output: true

# Frontpage settings
frontpage:
  header: >
    Instilling data collection practices with
    integrity and freedom
  lead: >
    Reclaim agency over your personal information,
    with the opportunity to make your data available
    for academics and researchers to further study
    across all aspects of human health, society, and culture

collections:
- frontpage_sections

# Build settings
markdown: kramdown
